CREATE DATABASE IF NOT EXISTS notes_eleves;


CREATE USER 'dvp'@'%' IDENTIFIED BY  'hello';
GRANT USAGE ON * . * TO  'dvp'@'%' IDENTIFIED BY  '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT SELECT , INSERT , UPDATE ON  `notes\_eleves` . * TO  'dvp'@'%';